### ISSUE TITLE
nie działa

### ISSUE THREAD

**Issue by mariusz442** [Margonem/OldMargonem#3]
Fatal error: Uncaught Error: Call to undefined function mysql_select_db() in C:\ksamp\htdocs\OldMargonem-master\MAEGONEM_pliki\php\mysql-connect.php:9 Stack trace: #0 C:\ksamp\htdocs\OldMargonem-master\MAEGONEM_pliki\game.php(2): require_once() #1 {main} thrown in C:\ksamp\htdocs\OldMargonem-master\MAEGONEM_pliki\php\mysql-connect.php on

**Comment by HunterAzar** [comment]
musiałbyś pobrać xamppa z PHP w wersji 5.6, ponieważ ten projekt używa starszej wersji PHP

**Comment by HunterAzar** [comment]
lub pobawić się i pozmieniać na funkcje z obecnego PHP 8 lub 7

**Comment by HunterAzar** [comment]
@mariusz442 zamknij ten wątek
